config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
<<<<<<< HEAD
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
  resources :posts, only: [:new, :create, :destroy]
  resources :account_activations, only: [:edit]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validate :picture_size

  def picture_size
    if picture.size > 5.megabytes
      error.add(:picture, "投稿する画像は5MB以下にしてください")
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destory]
  before_action :correct_user, only: [:destroy]
  PER = 30

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "投稿しました"
      redirect_to root_path
    else
      @feed_items = []
      render "static_pages/top"
    end
  end

  def destroy
    @post.destroy
    flash[:success] = "ポストを削除しました"
    redirect_to request.referrer || root_path
  end

  def index
    @posts = Post.page(params[:page]).per(PER)
  end
end

  private
    def post_params
      params.require(:post).permit(:content, :picture)
    end

    def correct_user
      @post = current_user.posts.find_by(id: params[:id])
      redirect_to root_path if @post.nil?
    end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<li id="post-<%= post.id %>">
  <%= link_to image_tag(post.user.gravatar_url(:size => 50)), post.user %>
  <span class="user"><%= link_to post.user.name, post.user %></span>
  <span class="content">
    <%= post.content %>
    <%= image_tag post.picture.url if post.picture? %>
  </span>
  <span class="timestamp">
    <%= time_ago_in_words(post.created_at) %>前に投稿
    <% if correct_user?(post.user) %>
      <%= link_to "削除", post_path(post), method: :delete, data: { confirm: "本当に削除しますか？" } %>
    <% end %>
  </span>
</li>

app/views/posts/index.html.erb
<% provide(:title, "ポスト一覧") %>
<h1>ポスト一覧</h1>
<ol class="posts">
  <%= render @posts %>
</ol>
<%= paginate @posts %>

app/views/posts/new.html.erb
<h1>Posts#new</h1>

<%= form_for @post do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <%= f.label "コメントを書く" %>
  <%= f.text_field :content %>

  <%= f.submit "投稿する" %>
<% end %>