config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
<<<<<<< HEAD
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
  resources :posts, only: [:new, :create, :destroy]
  resources :account_activations, only: [:edit]
end

app/views/layouts/_footer.html.erb
<footer class="footer navbar">
  <div class="container">
    Developed by Shuhei Yoshino
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Instaclone", root_path %></li>
      </ul>
    </nav>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Instaclone", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "ユーザー一覧", users_path %></li>
        <% if logged_in? %>
          <li><%= link_to "投稿する", new_post_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.name %><b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "マイページ", current_user %></li>
              <li><%= link_to "登録内容の変更", edit_user_path(current_user) %></li>
              <li><%= link_to "ログアウト", logout_path, method: :delete %></li>
              <li><%= link_to "退会", current_user, method: :delete, data: { confirm: "本当に退会しますか？" } %></li>
            </ul>
          </li>
        <% else %>
          <%= link_to "ログイン", login_path %>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if It IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>